### PR TITLE
Generate reference doc for modules from starters

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-stream-app-starters#2

### CODE REVIEW

**Comment by sobychacko** [comment]
@ericbottard I wonder if we should put the readme as part of the generated application. Most of the content in the readme is geared toward the application (things like the properties to use, java command to run the app etc.). Since the readme is now part of the starter project, the end user who is running the app will not see that readme. It might be convenient if we could make the readme available as part of the app itself. Your thoughts?

**Comment by ericbottard** [comment]
Agreed, the README.adoc should be copied over by the plugin (should be configurable ala `<resources>` pattern, I would say even)

**Comment by sobychacko** [comment]
sure, we will use the plugin to copy them over from starters.

**Comment by sobychacko** [comment]
merged.

**Pull request closed without merging**
