### PR TITLE
Adding missing prefix in Trigger constants, updating docs

### LINKED ISSUE #200: Trigger constants is missing the prefix defined in TriggerProperties implementations

### PR DESCRIPTION
**Pull request by sobychacko**
Resolves #200

### CODE REVIEW

**Comment by markpollack** [comment]
I think I left off the prefix on purpose so that the trigger (cron) configuration class could be used across multiple apps.  Isn't a cron expression used in the task launcher ?  The key goal is to have reuse of the trigger configuration across different apps, of this PR achieves that, maybe it was just an oversight.

**Comment by markfisher** [comment]
Without this PR, cron expressions were not even being recognized by either `time` or `trigger` source apps (fixed-delay with the 1 second default was always being used, even if `trigger.cron` or `trigger.date` were provided). The reason was that the conditional property key was simply "cron" whereas the actual property is `trigger.cron`, and according to the README for `triggertask` that also expects `trigger.cron`, but that should be tested as well, since the README was at odds with reality for these other 2 prior to this PR. cc @cppwfs

**Comment by markpollack** [comment]
Ok, that makes sense then, tx

**Comment by markfisher** [comment]
LGTM; merged

**Pull request merged**
