### PR TITLE
Fix default for trigger, remove defaults from javadoc.

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-stream-app-starters#32

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@ericbottard Should these `javadoc` and the `additional-spring-configuration-metadata.json` changes be applied to other `trigger` configuration property class `TriggerPropertiesMaxMessagesDefaultOne`?

**Comment by ericbottard** [comment]
I believe so, yes. Good catch (I was looking at app documentation one-by-one)

**Comment by ericbottard** [comment]
Currently working for a fix for https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/32, which I'll make part of this PR as well

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Squashed, rebased and merged as 1c072d96b90b9fb3cc15a7f040fc67a60c6dc572

**Pull request closed without merging**
