### PR TITLE
Remove SpelExpressionConverterConfiguration

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-stream-app-starters#167

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
It looks like there are still few other app starters that still use `SpelExpressionConverterConfiguration` (For instance: FtpSinkConfiguration, CounterSinkConfiguration, AggregateCounterSinkConfiguration etc.,)

**Comment by ericbottard** [comment]
Rebased ans addressed review comments. Not sure how those escaped me, sorry

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Squashed and merged as c500868080f2292e5a433fc884f11a8f3d22a047

**Pull request closed without merging**
