### PR TITLE
GH-79: Amazon S3 Source & Sink

### PR DESCRIPTION
**Pull request by artembilan**
Fixes spring-cloud/spring-cloud-stream-app-starters/issues/79
- Add `app-starter-s3-common` module to keep common `AmazonS3` bean definition and dependencies
- Add `AmazonS3SourceConfiguration` and respective `AmazonS3SourceProperties`
- The application is fully similar to the existing (S)FTP apps
- Add `PollerMetadata.DEFAULT_POLLER` alias for the `defaultPoller` `PollerMetadata` bean to let any `MessageSource<?>` application just rely on the default Spring Integration infrastructure
- Override the default `localDir` in the `AbstractRemoteFileSourceProperties` from the `AmazonS3SourceProperties`. See https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/94

### CODE REVIEW

**Comment by artembilan** [comment]
Note: this isn't finished yet. There is no `Sink` implementation.
But, at least, you have already a chance to review `Source` and provide feedback for the infrastructure changes.

Another observation: looks like all those properties in the `spring-cloud-stream-app-descriptor` can be generated as well. Any thoughts?

**Comment by artembilan** [comment]
H-m-m.
The app generator did this for me:

``` java
@SpringBootApplication
@Import(org.springframework.cloud.stream.app.s3.source.S3SourceConfiguration.class)
public class S3SourceKafkaApplication {

    public static void main(String[] args) {
        SpringApplication.run(S3SourceKafkaApplication.class, args);
    }
}
```

When my source class is like `AmazonS3SourceConfiguration`.
Have I missed some naming conventions? :cry: 

CC @sobychacko

**Comment by sobychacko** [comment]
@artembilan The configuration class is imported using the convention provided as the artifact id provided as the generated app in https://github.com/spring-cloud/spring-cloud-stream-app-starters/blob/master/spring-cloud-stream-app-generator/pom.xml#L35.

For ex, time-source will be converted as TimeSourceConfiguration. In your case, since you provided the generated app artifact id as s3-source, it is looking for a class named `S3SourceConfiugration`. If you want it to be `AmazonS3SourceConfiguration`, then your artifact id should be `amazon-s3-source-configuration`. But, this would mean that you would have to change a bunch of other things such as renaming the starter artifact etc.

Here is what you may want to do. 

Pass a parameter to the generated app artifact id called `autoConfigClass` and define the class there. For example,

``` xml
<s3-source>
      <autoConfigClass>foo.bar.FooBar.class</autoConfigClass>
</s3-source>
```

Or you can rename the class `AmazonS3SourceConfiguration` to simply `S3SourceConfiguration`

**Comment by sobychacko** [comment]
@artembilan `spring-cloud-stream-app-descriptor` entries could be auto-generated. We never got to it during the last iteration. We should make it as an enhancement to the maven plugin. I will write a GH issue for that.

**Comment by artembilan** [comment]
See https://github.com/spring-cloud/spring-cloud-stream-app-maven-plugin/issues/6 for the `spring-cloud-stream-app-descriptor` subject.

**Comment by artembilan** [comment]
@sobychacko , thank you for your feedback and some advices.
Meanwhile I really can do changes anyway, I'd like to discuss with you the proper name.
Will `s3` (`sqs`, `sns` etc.) enough for our roadmap? Or should be really to prefix them with the `amazon`?
CC @sabbyanandan 

Another question (and seems for me I raised it already in the `mail-source` PR): why don't we just rely on the project level Maven Wrapper? Why do I need to reinstall and reconfigure my local Maven to meet project requirements, when we simply can make end-user just use `mvnw` together with our custom `.settings.xml` ?

**Comment by sobychacko** [comment]
@artembilan good point about the maven wrapper - we should change the generate script to use that.

**Comment by artembilan** [comment]
OK. I can do that with this PR, too. 
BTW any feedback for the `mail-source` near by? It is ready to merge, but I'd like to loop my polishing with someone else to be sure that I didn't miss anything.

**Comment by sobychacko** [comment]
@artembilan @sabbyanandan @markpollack  If we are going to have more Amazon related source/sink as Artem mentioned above, it would be better to create a top-level folder called amazon.

For example:

> spring-cloud-stream-app-starters
> |--------------amazon
> |----------------------spring-cloud-starter-stream-sink-amazon-s3
> |----------------------spring-cloud-starter-stream-source-amazon-s3
> |----------------------spring-cloud-starter-stream-source-amazon-sqs etc.

That way you can have a class named AmazonS3SourceConfiguration or AmazonS3SinkConfiguration.

If we don't want to qualify with "Amazon", then you need to change the configuration class from AmazonS3SourceConfiguraiton to S3SourceConfiguration. (Or use the flag mentioned in the above comment to force it to use a different name).

**Comment by sabbyanandan** [comment]
>  it would be better to create a top-level folder called amazon

👍; yes, we have other types of aws-applications in the pipeline. Perhaps we could name the top-level directory as `aws`?

**Comment by artembilan** [comment]
Well, technically it is just logical name and it doesn't affect the runtime.
I think I'm fine with an existing protocol-specific hierarchy, where `s3`, `sqs`, `sns` `kinesis` etc. are some kind of them, too. So, for me to go ahead with existing structure is more intuitive.
We may reconsider in the future, though.

Right now my concern is just like this:
1. Should we call it like `aws-s3`, `aws-sqs` etc?
2. Therefore should the target apps have similar name with `aws-` prefix?
3. Should the target SCDF modules be called similar way with `aws-` prefix?

Or we just fine with more short, specific name and something like `s3 | cassandra` is the best choice for end users?

That is my point.

**Comment by artembilan** [comment]
OTOH with the `aws-` prefix the modules in the project will be co-located. So, it's more easier to navigate and develope :smile: 
Not a problem for me to rename, but I am against (yet) the logic top-level `aws` folder.

**Comment by sobychacko** [comment]
Even if the app name is something like aws-s3-source, one can register it as simply s3 in SCDF, right? I like both options, however, we went with a grouping based hierarchy for the app-starters (such as jdbc, jms, file etc.), so i might lean towards the aws grouping option. But its up to you. If you keep the current structure, you have to rename the AmaonS3SourceConfiguration to S3SourceConfiguration or use that autoConfigClass option to force the Amazon\* name in the generated app.

**Comment by sobychacko** [comment]
@artembilan you may want to just rename the class AmazonS3SourceConfiguration to S3SourceConfiguration. That way we can still get the PR moving forward and come back to the discussion of grouping later. What do you think?

**Comment by artembilan** [comment]
Well, @sobychacko , since I see that you are assigned to the PR for review. I think we can arrange some lunch meeting and work together for review/fixing :smile: 

But I'm fine to leave it as is now and just adjust config to use the `<autoConfigClass>` hint.

BTW, I wonder if we don't have similar naming issue with any other our existing apps.

**Comment by sobychacko** [comment]
For all current starters, we either used the required naming convention or use the hint for the main Configuration class. For instance, for jdbc-sink it is JdbcSinkConfiguration, for scriptable-transform processor it is ScriptableTransformProcessorConfiguration so on and so forth.

**Comment by artembilan** [comment]
Pushed some further steps.

**Comment by sobychacko** [comment]
@artembilan @sabbyanandan It would be nice to have some integration tests to validate real interactions  with AWS/S3.

May be create a test that connects to a real S3 instance which can only be triggered manually for verification purposes? Thoughts?

**Comment by sobychacko** [comment]
The context load tests in the generated apps are failing. You might want to add an ignore for those tests as they need a real AWS connection.

`generateApps`
`cd apps`
`mvn clean package -pl :s3-source-kafka,s3-source-rabbit`

**Comment by artembilan** [comment]
Not sure in your observation, but I see this `<skipTests>true</skipTests>` in their poms.
Have just copy/pasted your command:

```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ s3-source-rabbit ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ s3-source-rabbit ---
[INFO] Building jar: D:\SpringIO\spring-cloud\spring-cloud-stream-app-starters\apps\s3-source-rabbit\target\s3-source-rabbit-1.0.0.BUILD-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.3.3.RELEASE:repackage (default) @ s3-source-rabbit ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3-source-kafka ................................... SUCCESS [12.096s]
[INFO] s3-source-rabbit .................................. SUCCESS [0.383s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.209s
```

What am I missing ?

**Comment by sobychacko** [comment]
Tests are skipped by default when you do `mvn package` on the generated apps because those tests require kafka and rabbit running. However, we can force them to run the tests by saying -DskipTests=false on the command line. Its not a big issue at the moment, because no one is running those tests by skipTests=false, but we might start running those on CI at some point. If you want those context load tests to not run under any circumstance, as in the case of Cassandra and Gemfire tests, then you need to manually ignore them. See the generator pom.xml for examples of those.

**Comment by artembilan** [comment]
Yeah! Agree. That is the fact that we can't load this AWS context without any real options.
So, will ignore them.

Thank you for assistant!

**Comment by artembilan** [comment]
Pushed

**Comment by artembilan** [comment]
Pushed some dependencies polishing

**Comment by artembilan** [comment]
Just for some update where I am.

According to recommendation from the [Spring Cloud AWS](https://github.com/spring-cloud/spring-cloud-aws#running-integration-tests) main page:

>  Creating these resources takes time and costs money, because every instance creation is charged with a one hour usage. Therefore Spring Cloud AWS does not execute the integration tests by default.

I'm going to: 
1. create a new projects module, e.g. `aws-integration-tests`;
2. Use for the running of those integration tests the [Maven Failsafe Plugin](http://maven.apache.org/surefire/maven-failsafe-plugin/index.html) (Not sure yet how it lives together with the Surefire one);
3. Follow with the standard AWS recommendation for such a case and use [AWS CloudFormation](https://aws.amazon.com/cloudformation/) to run/stop the Stack by some template for our integration testing purpose;
4. To save some time (and money) we will have there only one `IT` class for all our potential AWS apps. The AWS stack will be created only once from the `@BeforeClass`

Hope I haven't missed anything :smile: 

Any comments welcome!

**Comment by sobychacko** [comment]
@artembilan As discussed, we will merge this PR and you will do the testing work mentioned above through a different PR.

**Comment by sobychacko** [comment]
rebased, polished and merged.

**Comment by artembilan** [comment]
As pointed above: Merged

**Pull request closed without merging**
